import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header/header";
import "@fortawesome/fontawesome-free/css/all.min.css"
import "swiper/css";
import Footer from "@/components/layout/footer/footer";
import Providers from "@/redux/provider/providers";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}`}
      >
        <Providers>
        <Header/>
        {children}
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}
