import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import "@fortawesome/fontawesome-free/css/all.min.css";
import "swiper/css";

import Providers from "@/redux/provider/providers";
import LayoutWrapper from "@/components/layout/layoutWrapper/layoutWrapper";
import { Toaster } from "sonner";
// import LayoutWrapper from "@/components/layout/LayoutWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <Providers>
          <Toaster richColors position="top-center" duration={3000} />
          <LayoutWrapper>{children}</LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}
